### ISSUE TITLE
Can't compile - missed pthread library

### ISSUE THREAD

**Issue by matvey00z** [yeplastun/QRDecomposition#1]
Do as you wrote:
$ cd tmp
$ cmake .
$ make
Linking CXX executable main
libmatrix.a(matrix.cpp.o): In function `Matrix::inverse(int)':
matrix.cpp:(.text+0x2fa5): undefined reference to `pthread_create'
matrix.cpp:(.text+0x2fdf): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[2]: *** [main] Error 1
make[1]: *** [CMakeFiles/main.dir/all] Error 2
make: *** [all] Error 2

Seems that you forgot to link pthread library. 
Built successfully with the following command:
$ g++ main.cpp matrix.cpp -lm -pthread -O3 -std=c++11

**Comment by yeplastun** [comment]
It is ok when I try to compile it on with g++ on MacOs without -lpthread flag, but I added it to CMakeLists.txt . Thanks for response.
